# Generated by Django 4.2 on 2023-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firstname",
            field=models.CharField(default=" ", max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="lastname",
            field=models.CharField(default=" ", max_length=30),
        ),
    ]
