# Generated by Django 4.2 on 2023-05-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_firstname_user_lastname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="user",
            name="lastname",
        ),
    ]
