# Generated by Django 4.2 on 2023-05-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="site_images"),
        ),
        migrations.AddField(
            model_name="site",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
