# Generated by Django 4.2 on 2023-06-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="image",
        ),
        migrations.RemoveField(
            model_name="site",
            name="url",
        ),
    ]
