# Generated by Django 4.2 on 2023-07-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_remove_site_image_remove_site_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Silo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=50)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.line"
                    ),
                ),
            ],
        ),
    ]
