# Generated by Django 4.2 on 2023-07-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_user_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="team",
        ),
    ]
