# Generated by Django 4.2 on 2023-07-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_user_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Nouveau", "Nouveau"),
                    ("Gestionnaire de production", "Gestionnaire de production"),
                    ("Gestionnaire de stock", "Gestionnaire de stock"),
                    ("Responsable de production", "Responsable de production"),
                    ("Admin", "Admin"),
                ],
                max_length=30,
            ),
        ),
    ]
