# Generated by Django 4.2 on 2023-07-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="address",
            field=models.CharField(default="mail", max_length=50),
            preserve_default=False,
        ),
    ]
