# Generated by Django 4.2 on 2023-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_site_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="address",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
