# Generated by Django 4.2 on 2023-05-18 10:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0008_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("MP", "MP"), ("PSF", "PSF"), ("PF", "PF")],
                        max_length=30,
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ReasonStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("Confirmed1", "Confirmed1"),
                            ("Confirmed2", "Confirmed2"),
                            ("Refused1", "Refused1"),
                            ("Refused2", "Refused2"),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("n_lot", models.CharField(max_length=30)),
                ("prod_day", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("6H-14H", "6H-14H"),
                            ("14H-22H", "14H-22H"),
                            ("18H-6H", "18H-6H"),
                            ("6H-18H", "6H-18H"),
                            ("8H-18H", "8H-18H"),
                            ("22H-8H", "22H-8H"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "qte_sac_prod",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "nbt_melange",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("observation", models.TextField()),
                (
                    "qte_global",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qte_sac_reb",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qte_sac_rec",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("n_lot_rec", models.CharField(max_length=30)),
                ("observation_rec", models.TextField()),
                (
                    "etat_s1",
                    models.CharField(
                        choices=[
                            ("Plein", "Plein"),
                            ("Vide", "Vide"),
                            ("1/3", "1/3"),
                            ("1/2", "1/2"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "etat_s2",
                    models.CharField(
                        choices=[
                            ("Plein", "Plein"),
                            ("Vide", "Vide"),
                            ("1/3", "1/3"),
                            ("1/2", "1/2"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "etat_s3",
                    models.CharField(
                        choices=[
                            ("Plein", "Plein"),
                            ("Vide", "Vide"),
                            ("1/3", "1/3"),
                            ("1/2", "1/2"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "etat_s4",
                    models.CharField(
                        choices=[
                            ("Plein", "Plein"),
                            ("Vide", "Vide"),
                            ("1/3", "1/3"),
                            ("1/2", "1/2"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "etat_s5",
                    models.CharField(
                        choices=[
                            ("Plein", "Plein"),
                            ("Vide", "Vide"),
                            ("1/3", "1/3"),
                            ("1/2", "1/2"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "etat_s7",
                    models.CharField(
                        choices=[
                            ("Plein", "Plein"),
                            ("Vide", "Vide"),
                            ("1/3", "1/3"),
                            ("1/2", "1/2"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        limit_choices_to={"role": "Gestionnaire de production"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.line"
                    ),
                ),
                (
                    "prod_product",
                    models.ForeignKey(
                        limit_choices_to={"type": "PF"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prod_product",
                        to="report.product",
                    ),
                ),
                (
                    "rec_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rec_product",
                        to="report.product",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MPConsumed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qte_consumed",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("observation", models.TextField()),
                (
                    "product",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("type", "MP"), ("type", "PSF"), _connector="OR"
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.product",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.report"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Arret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RIAS", "RIAS"),
                            ("Planned", "Planned"),
                            ("Unplanned", "Unplanned"),
                        ],
                        max_length=30,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("finish_at", models.DateTimeField()),
                ("actions", models.TextField()),
                (
                    "reason_stop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="report.reasonstop",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.report"
                    ),
                ),
            ],
        ),
    ]
