# Generated by Django 4.2 on 2023-05-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("Matière première", "Matière première"),
                    ("Produit Semi-fini", "Produit Semi-fini"),
                    ("Produit Fini", "Produit Fini"),
                ],
                max_length=30,
            ),
        ),
    ]
