# Generated by Django 4.2 on 2023-06-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_alter_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpconsumed",
            name="product",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("type", "Matière première"),
                    ("type", "Produit Semi-fini"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.product",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="prod_product",
            field=models.ForeignKey(
                limit_choices_to={"type": "Produit Fini"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prod_product",
                to="report.product",
            ),
        ),
    ]
