# Generated by Django 4.2 on 2023-06-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_alter_mpconsumed_product_alter_report_prod_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="state",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Confirmed1", "Confirmed1222"),
                    ("Confirmed2", "Confirmed2"),
                    ("Refused1", "Refused1"),
                    ("Refused2", "Refused2"),
                    ("Canceled", "Canceled"),
                ],
                max_length=30,
            ),
        ),
    ]
