# Generated by Django 4.2 on 2023-06-08 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("report", "0004_alter_report_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="state",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Confirmed", "Confirmed"),
                    (
                        "Validated by Gestionaire de Stock",
                        "Validated by Gestionaire de Stock",
                    ),
                    (
                        "Validé par RP",
                        "Validé par RP",
                    ),
                    (
                        "Refused by Gestionaire de Stock",
                        "Refused by Gestionaire de Stock",
                    ),
                    (
                        "Refused by Responsable de Production",
                        "Refused by Responsable de Production",
                    ),
                    ("Canceled", "Canceled"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="Validation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_state",
                    models.CharField(
                        choices=[
                            ("Confirmed", "Confirmed"),
                            (
                                "Validated by Gestionaire de Stock",
                                "Validated by Gestionaire de Stock",
                            ),
                            (
                                "Validé par RP",
                                "Validé par RP",
                            ),
                            (
                                "Refused by Gestionaire de Stock",
                                "Refused by Gestionaire de Stock",
                            ),
                            (
                                "Refused by Responsable de Production",
                                "Refused by Responsable de Production",
                            ),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("Confirmed", "Confirmed"),
                            (
                                "Validated by Gestionaire de Stock",
                                "Validated by Gestionaire de Stock",
                            ),
                            (
                                "Validé par RP",
                                "Validé par RP",
                            ),
                            (
                                "Refused by Gestionaire de Stock",
                                "Refused by Gestionaire de Stock",
                            ),
                            (
                                "Refused by Responsable de Production",
                                "Refused by Responsable de Production",
                            ),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=40,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("refusal_reason", models.TextField()),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.report"
                    ),
                ),
            ],
        ),
    ]
