# Generated by Django 4.2 on 2023-06-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0005_alter_report_state_validation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validation",
            name="new_state",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Confirmed", "Confirmed"),
                    (
                        "Validated by Gestionaire de Stock",
                        "Validated by Gestionaire de Stock",
                    ),
                    (
                        "Validé par RP",
                        "Validé par RP",
                    ),
                    (
                        "Refused by Gestionaire de Stock",
                        "Refused by Gestionaire de Stock",
                    ),
                    (
                        "Refused by Responsable de Production",
                        "Refused by Responsable de Production",
                    ),
                    ("Canceled", "Canceled"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="validation",
            name="old_state",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Confirmed", "Confirmed"),
                    (
                        "Validated by Gestionaire de Stock",
                        "Validated by Gestionaire de Stock",
                    ),
                    (
                        "Validé par RP",
                        "Validé par RP",
                    ),
                    (
                        "Refused by Gestionaire de Stock",
                        "Refused by Gestionaire de Stock",
                    ),
                    (
                        "Refused by Responsable de Production",
                        "Refused by Responsable de Production",
                    ),
                    ("Canceled", "Canceled"),
                ],
                max_length=40,
            ),
        ),
    ]
