# Generated by Django 4.2 on 2023-06-13 17:11

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_remove_site_image_remove_site_url"),
        ("report", "0006_alter_validation_new_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="arret",
            name="type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="type",
        ),
        migrations.RemoveField(
            model_name="report",
            name="etat_s1",
        ),
        migrations.RemoveField(
            model_name="report",
            name="etat_s2",
        ),
        migrations.RemoveField(
            model_name="report",
            name="etat_s3",
        ),
        migrations.RemoveField(
            model_name="report",
            name="etat_s4",
        ),
        migrations.RemoveField(
            model_name="report",
            name="etat_s5",
        ),
        migrations.RemoveField(
            model_name="report",
            name="etat_s7",
        ),
        migrations.RemoveField(
            model_name="report",
            name="n_lot_rec",
        ),
        migrations.RemoveField(
            model_name="report",
            name="observation",
        ),
        migrations.RemoveField(
            model_name="report",
            name="rec_product",
        ),
        migrations.AddField(
            model_name="arret",
            name="observation",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="line",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.line",
            ),
        ),
        migrations.AddField(
            model_name="reasonstop",
            name="line",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.line",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 6, 13, 17, 11, 5, 818517, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="report",
            name="nbt_pallete",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="passed_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 6, 13, 17, 11, 21, 346439, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="qte_rec",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="prod_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prod_product",
                to="report.product",
            ),
        ),
        migrations.DeleteModel(
            name="MPConsumed",
        ),
        migrations.AddField(
            model_name="arret",
            name="type_stop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="report.typestop",
            ),
        ),
        migrations.AddField(
            model_name="reasonstop",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.typestop",
            ),
        ),
    ]
