# Generated by Django 4.2 on 2023-06-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_remove_site_image_remove_site_url"),
        ("report", "0007_typestop_remove_arret_type_remove_product_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reasonstop",
            name="line",
        ),
        migrations.AddField(
            model_name="typestop",
            name="line",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.line",
            ),
        ),
    ]
