# Generated by Django 4.2 on 2023-06-15 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0008_remove_reasonstop_line_typestop_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="poids_melange",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
