# Generated by Django 4.2 on 2023-06-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0009_report_poids_melange"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arret",
            name="finish_at",
        ),
        migrations.RemoveField(
            model_name="arret",
            name="start_at",
        ),
        migrations.AddField(
            model_name="arret",
            name="duration",
            field=models.TimeField(null=True),
        ),
    ]
