# Generated by Django 4.2 on 2023-06-15 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0010_remove_arret_finish_at_remove_arret_start_at_and_more"),
    ]

    operations = [
    ]
