# Generated by Django 4.2 on 2023-06-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0011_alter_report_passed_time"),
    ]

    operations = [
    ]
