# Generated by Django 4.2 on 2023-06-17 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0012_remove_report_passed_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="passed_time",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
