# Generated by Django 4.2 on 2023-06-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0013_report_passed_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arret",
            name="duration",
        ),
    ]
