# Generated by Django 4.2 on 2023-06-17 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0014_remove_arret_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="arret",
            name="duration",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
