# Generated by Django 4.2 on 2023-07-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_silo"),
        ("report", "0018_mpconsumed"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtatSilo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("Plein", "Plein"),
                            ("Vide", "Vide"),
                            ("1/4", "1/4"),
                            ("1/2", "1/2"),
                            ("1/3", "1/3"),
                            ("2/3", "2/3"),
                            ("3/4", "3/4"),
                        ],
                        max_length=5,
                    ),
                ),
                ("observation", models.TextField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.report"
                    ),
                ),
                (
                    "silo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.silo",
                    ),
                ),
            ],
        ),
    ]
