# Generated by Django 4.2 on 2023-07-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0020_alter_report_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="shift",
            field=models.CharField(
                choices=[
                    ("6H-14H", "6H-14H"),
                    ("14H-22H", "14H-22H"),
                    ("18H-6H", "18H-6H"),
                    ("6H-18H", "6H-18H"),
                    ("8H-18H", "8H-18H"),
                    ("22H-8H", "22H-8H"),
                ],
                default=0,
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
