# Generated by Django 4.2 on 2023-07-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_horaire_site_horaires"),
        ("report", "0021_alter_report_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="shift",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.horaire",
            ),
        ),
    ]
