# Generated by Django 4.2 on 2023-07-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0024_remove_arret_duration_arret_hour_arret_minutes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="qte_global",
            new_name="qte_tn",
        ),
    ]
