# Generated by Django 4.2 on 2023-07-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0025_rename_qte_global_report_qte_tn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="state",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Confirmé", "Confirmé"),
                    ("Validé par GS", "Validé par GS"),
                    ("Validé par DI", "Validé par DI"),
                    ("Refusé par GS", "RRefusé par GS"),
                    ("Refusé par DI", "Refusé par DI"),
                    ("Annulé", "Annulé"),
                ],
                max_length=40,
            ),
        ),
    ]
