# Generated by Django 4.2 on 2023-07-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0026_alter_report_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validation",
            name="new_state",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Confirmé", "Confirmé"),
                    ("Validé par GS", "Validé par GS"),
                    ("Validé par RP", "Validé par RP"),
                    ("Refusé par GS", "Refusé par GS"),
                    ("Refusé par RP", "Refusé par RP"),
                    ("Annulé", "Annulé"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="validation",
            name="old_state",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Confirmé", "Confirmé"),
                    ("Validé par GS", "Validé par GS"),
                    ("Validé par RP", "Validé par RP"),
                    ("Refusé par GS", "Refusé par GS"),
                    ("Refusé par RP", "Refusé par RP"),
                    ("Annulé", "Annulé"),
                ],
                max_length=40,
            ),
        ),
    ]
