# Generated by Django 4.2 on 2023-07-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_user_team"),
        ("report", "0027_alter_validation_new_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.site",
            ),
        ),
    ]
