# Generated by Django 4.2 on 2023-07-12 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0028_report_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arret",
            name="hour",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
    ]
